trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: 'SQL-Server-Creation'
    backendServiceArm: 'RC-MPN-EMP-PRATIK-SAPKOTA(ab2dfb8a-e408-48ef-bc98-0270528fab33)'
    backendAzureRmResourceGroupName: 'TerraformExample01RG'
    backendAzureRmStorageAccountName: 'terraformexample01sbik3c'
    backendAzureRmContainerName: 'demostatesave'
    backendAzureRmKey: 'terraform.tfstate'
- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: 'SQL-Server-Creation'
    commandOptions: '-var="password=$(SQL_PASSWORD)" -var="ip_address=$(IP_ADDRESS)"'
    environmentServiceNameAzureRM: 'RC-MPN-EMP-PRATIK-SAPKOTA(ab2dfb8a-e408-48ef-bc98-0270528fab33)'
    
- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: 'SQL-Server-Creation'
    commandOptions: '-var="password=$(SQL_PASSWORD)" -var="ip_address=$(IP_ADDRESS)"'
    environmentServiceNameAzureRM: 'RC-MPN-EMP-PRATIK-SAPKOTA(ab2dfb8a-e408-48ef-bc98-0270528fab33)'